trainer:
  callbacks:
  - class_path: pytorch_lightning.callbacks.lr_monitor.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
  - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
    init_args:
      # monitor: 'val_loss'
      filename: '{epoch:03d}-{val_loss:.3f}-{val_dice:.3f}'
      monitor: 'val_dice'
      mode: max
      # save_weights_only: true
      save_last: false
      save_top_k: 1
      every_n_epochs: 1
      save_on_train_epoch_end: false
  default_root_dir: logs
  strategy: ddp_find_unused_parameters_false
